apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd_deployment
spec:
  selector:
    matchLabels:
      app: httpd_deployment
  replicas: 2
  template:
    metadata:
      name: deploy-pod
      labels:
        app: httpd_deployment
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          ports:
            - containerPort: 8080

