apiVersion: v1
kind: Pod
metadata:
  name: dev-nginx-pod
  namespace: dev
  labels:
    nginx: latest
spec:
  containers:
  - name: dev-nginx-pod
    image: nginx:latest
    ports:
    - containerPort: 80


# labels are attached to pod
# from selector we can use labels
