apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx_app
    type: front-end
spec:
  selector:
    matchLabels:
      app: nginx_app
      type: front-end
  replicas: 4
  template:
    metadata:
      name: nginx-replicaset
      labels:
        app: nginx_app
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest

# (pod+controller)= Rc or rs the difreence b/w rc vs rs is selector is mandtray in rs
# rs is only focus on replicas it cannot overwrite the image
# in deployment we can overwrite image